# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi-Vue-Plus
  # 版本
  version: ${ruoyi-vue-plus.version}
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 获取ip地址开关
  addressEnabled: true
server:
  port: 8090
# Spring配置
spring:
  application:
    name: RuoYi-Gateway
  profiles:
    active: @profiles.active@
