v2:
  #虚拟路径映射路径 2个文件路径一一对应 第一个为主存储，其他为配置相关
  xnljmap:
    #win服务器  本地 注意！！ 记住这个结尾有一个/
    oss: file:C:/Users/Administrator/IdeaProjects/go-view-serve-master/upload/
    #linux服务器
    #oss: file:/home/webapps/oss/
  #虚拟路径映射路径 end
  #本地存放地址 注意！！ 记住这个结尾没有/
  fileurl: C:/Users/Administrator/IdeaProjects/go-view-serve-master/upload
  #http://127.0.0.1:8080/oss/{yy}/2022-12-22/c83a77ae134a540c30daa6a0666fa945.md
  httpurl: http://127.0.0.1:8083/
  defaultFormat: .png

--- # 数据库配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 最大连接池数量
      maxPoolSize: 20
      # 最小空闲线程数量
      minIdle: 10
      # 配置获取连接等待超时的时间
      connectionTimeout: 30000
      # 校验超时时间
      validationTimeout: 5000
      # 空闲连接存活最大时间，默认10分钟
      idleTimeout: 600000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      maxLifetime: 1800000
      # 连接测试query（配置检测连接是否有效）
      connectionTestQuery: SELECT 1
      # 多久检查一次连接的活性
      keepaliveTime: 30000
