server:
  port: 9090
spring:
  application:
    name: ruoyi-monitor-admin
  profiles:
    active: @profiles.active@

logging:
  config: classpath:logback-plus.xml

--- # 监控中心服务端配置
spring:
  security:
    user:
      name: ruoyi
      password: 123456
  boot:
    admin:
      ui:
        title: RuoYi-Vue-Plus服务监控中心
      context-path: /admin

--- # Actuator 监控端点的配置项
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: ./logs/ruoyi-monitor-admin.log

--- # 监控配置
spring.boot.admin.client:
  # 增加客户端开关
  enabled: true
  # 设置 Spring Boot Admin Server 地址
  url: http://localhost:9090/admin
  instance:
    service-host-type: IP
    metadata:
      username: ${spring.boot.admin.client.username}
      userpassword: ${spring.boot.admin.client.password}
  username: ruoyi
  password: 123456

--- # mail 邮件发送
mail:
  enabled: false
  host: smtp.163.com
  port: 465
  # 是否需要用户名密码验证
  auth: true
  # 发送方，遵循RFC-822标准
  from: xxx@163.com
  # 用户名（注意：如果使用foxmail邮箱，此处user为qq号）
  user: xxx@163.com
  # 密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）
  pass: xxxxxxxxxx
  # 使用 STARTTLS安全连接，STARTTLS是对纯文本通信协议的扩展。
  starttlsEnable: true
  # 使用SSL安全连接
  sslEnable: true
  # SMTP超时时长，单位毫秒，缺省值不超时
  timeout: 0
  # Socket连接超时值，单位毫秒，缺省值不超时
  connectionTimeout: 0

# 服务通知
notify:
  mail:
    enabled: false
    to:
    subject: 系统通知
    template: "<html><body>
                  <p>服务名: <b>{}</b> ({})</p>
                  <p>状态: <b>{}</b> ({})</p>
                  <p>服务IP: <b>{}</b></p>
                  <p>时间: <b>{}</b></p>
               </body></html>"
  web-hook:
    enabled: false
    type: 0
    url:
    secret:
    keywords:
    template: |
      #### **{}通知**
      - **服务名**: {}
      - **实例ID**: {}
      - **状态**: {}
      - **服务IP**: {}
      - **时间**: {}
