export const shoppingCarList = '/pages/mall/shopping-car/shopping-car-list'
export const orderListPage = '/pages/mall/order/order-list'
export const orderCheck = '/pages/mall/order/order-check'
export const userAddressListPage = '/pages/mall/user/user-address-list'
export const goodsDetailPage = '/pages/mall/goods/goods-detail'
